version: '1.300.{build}'

# Skip re-build caused by tagged release
skip_tags: true

only_commits:
  message: /\[appveyor\]/

#skip_commits:
#  message: /\[travis\]/

branches:
  only:
    - master

artifacts:
  - path: "reaper_js_ReaScriptAPI*.*"
  
environment:
  matrix:

  - job_name: linux_64
    appveyor_build_worker_image: ubuntu
    
  - job_name: macOS_64
    appveyor_build_worker_image: macos

  - job_name: macOS_64_ARM
    appveyor_build_worker_image: macos-bigsur

for:
  - matrix: 
      only: 
        - job_name: linux_64
    install:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo apt-get update -q -y
      - sudo apt-get install -y g++-5 libgtk-3-dev gcc-5-multilib g++-5-multilib
    build_script:
      - gcc-5 -c -fPIC -xc ./WDL/libpng/*.c
      - gcc-5 -c -fPIC -xc ./WDL/jpeglib/*.c
      - gcc-5 -c -fPIC -xc ./WDL/zlib/*.c
      - gcc-5 -c -fPIC -xc ./WDL/kuba/*.c
      - g++-5 -fPIC -shared -std=c++14 -Wall -DSWELL_PROVIDED_BY_APP -I"./WDL/swell/" -I"./WDL/jpeglib/" -I"./WDL/lice" -I"./WDL/libpng" -I"./WDL/zlib/" -I"./WDL/kuba/" js_ReaScriptAPI.cpp "./WDL/swell/swell-modstub-generic.cpp" "./WDL/lice/lice_png_write.cpp" "./WDL/lice/lice_jpg.cpp" "./WDL/lice/lice_jpg_write.cpp" "./WDL/lice/lice_colorspace.cpp" "./WDL/lice/lice.cpp" *.o `pkg-config --cflags --libs gtk+-3.0` -o reaper_js_ReaScriptAPI64.so


  - matrix:
      only:
        - job_name: macOS_64
    build_script:
      - clang -c -arch x86_64 -fPIC -std=c90 -xc ./WDL/libpng/*.c 
      - clang -c -arch x86_64 -fPIC -std=c90 -xc ./WDL/jpeglib/*.c 
      - clang -c -arch x86_64 -fPIC -std=c90 -xc ./WDL/zlib/*.c 
      - clang -c -arch x86_64 -fPIC -std=c90 -xc ./WDL/kuba/*.c 
      - clang++  -arch x86_64 -fPIC -dynamiclib -undefined dynamic_lookup -std=c++17 -DSWELL_PROVIDED_BY_APP -I"./WDL/swell/" -I"./WDL/lice" -I"./WDL/jpeglib" -I"./WDL/libpng" -I"./WDL/zlib/" -I"./WDL/kuba/" js_ReaScriptAPI.cpp js_ReaScriptAPI_ObjC.mm "./WDL/swell/swell-modstub.mm" "./WDL/lice/lice_png_write.cpp" "./WDL/lice/lice_jpg.cpp" "./WDL/lice/lice_jpg_write.cpp" "./WDL/lice/lice_colorspace.cpp" "./WDL/lice/lice.cpp" *.o -framework AppKit -framework Cocoa -lc++ -stdlib=libc++ -o "reaper_js_ReaScriptAPI64.dylib"
    test_script:
      - file reaper_js_ReaScriptAPI64.dylib
      
  - matrix:
      only:
        - job_name: macOS_64_ARM
    build_script:
      - clang -c -arch arm64 -fPIC -std=c90 -xc ./WDL/libpng/*.c 
      - clang -c -arch arm64 -fPIC -std=c90 -xc ./WDL/jpeglib/*.c 
      - clang -c -arch arm64 -fPIC -std=c90 -xc ./WDL/zlib/*.c 
      - clang -c -arch arm64 -fPIC -std=c90 -xc ./WDL/kuba/*.c 
      - clang++  -arch arm64 -fPIC -dynamiclib -undefined dynamic_lookup -std=c++17 -DSWELL_PROVIDED_BY_APP -I"./WDL/swell/" -I"./WDL/lice" -I"./WDL/jpeglib" -I"./WDL/libpng" -I"./WDL/zlib/" -I"./WDL/kuba/" js_ReaScriptAPI.cpp js_ReaScriptAPI_ObjC.mm "./WDL/swell/swell-modstub.mm" "./WDL/lice/lice_png_write.cpp" "./WDL/lice/lice_jpg.cpp" "./WDL/lice/lice_jpg_write.cpp" "./WDL/lice/lice_colorspace.cpp" "./WDL/lice/lice.cpp" *.o -framework AppKit -framework Cocoa -lc++ -stdlib=libc++ -o "reaper_js_ReaScriptAPI64_ARM.dylib"
    test_script:
      - file reaper_js_ReaScriptAPI64_ARM.dylib

deploy:
  - provider: GitHub
    auth_token:
      secure: xak+nfVvqW+GAoOuBcLy2isGeQS/mPKtI1nnWsAL3Ajh163kUPIGw2qc8AdQtXV5
    artifact: reaper_js_ReaScriptAPI64.so
    on:
      job_name: linux_64
      
  - provider: GitHub
    auth_token:
      secure: xak+nfVvqW+GAoOuBcLy2isGeQS/mPKtI1nnWsAL3Ajh163kUPIGw2qc8AdQtXV5
    artifact: reaper_js_ReaScriptAPI64.dylib
    on:
      job_name: macOS_64

  - provider: GitHub
    auth_token:
      secure: xak+nfVvqW+GAoOuBcLy2isGeQS/mPKtI1nnWsAL3Ajh163kUPIGw2qc8AdQtXV5
    artifact: reaper_js_ReaScriptAPI64_ARM.dylib
    on:
      job_name: macOS_64_ARM
